[package]
name = "xenet-npcap-helper"
version = "0.2.0"
edition = "2021"
authors = ["shellrow <shellrow@protonmail.com>"]
description = "Helper crate for managing the installation of npcap on Windows, providing essential support for the xenet"
repository = "https://github.com/shellrow/xenet"
readme = "../../README.md"
keywords = ["network", "windows"]
categories = ["network-programming"]
license = "MIT"

[dependencies]

[target.'cfg(windows)'.dependencies]
home = "0.5"
winreg = "0.50"
privilege = "0.3"
sha2 = "0.10"
zip = "0.6"
reqwest = { version = "0.11", features = ["blocking"], optional = true }
inquire = { version = "0.6", optional = true }

[features]
default = ["download"]
download = ["reqwest"]
interactive = ["inquire"]
